# Generated by Django 5.2.8 on 2025-11-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('green_duration', models.PositiveIntegerField(help_text='Green duration (seconds)')),
                ('yellow_duration', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_phase', models.CharField(choices=[('NS_GREEN', 'North-South Green'), ('NS_YELLOW', 'North-South Yellow'), ('EW_GREEN', 'East-West Green'), ('EW_YELLOW', 'East-West Yellow'), ('ALL_RED', 'All Red')], default='ALL_RED', max_length=10)),
                ('previous_phase', models.CharField(choices=[('NS_GREEN', 'North-South Green'), ('NS_YELLOW', 'North-South Yellow'), ('EW_GREEN', 'East-West Green'), ('EW_YELLOW', 'East-West Yellow'), ('ALL_RED', 'All Red')], default='EW_YELLOW', max_length=10)),
                ('last_phase_change', models.DateTimeField(auto_now_add=True)),
                ('active_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trafficplan')),
            ],
        ),
    ]
